import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";
import { useSpring } from "@react-spring/core";
import { a } from "@react-spring/web";
import Scene from "../components/Scene";
import { useEffect, useRef, useState } from "react";

export default function Home() {
  // This spring controls the background and the svg fill (text color)
  // const [{ background, fill }, set] = useSpring({ background: "#f0f0f0", fill: "#202020" }, []);
  const canvas = useRef(null);
  const [devicePixelRatio, setDevicePixelRatio] = useState(1);
  useEffect(() => {
    if (!canvas.current) return;
    setDevicePixelRatio(window.devicePixelRatio);
  }, [canvas]);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col md:flex-row h-screen w-full">
        <div className="flex-1 flex flex-col justify-center pl-12">
          <div className="text-8xl uppercase font-header mb-12">Nick Oelsner</div>
          <div className="text-4xl">Frontend Developer at Mondo Robot</div>
        </div>
        <Canvas className="flex-1" ref={canvas} dpr={[1, 2]}>
          <Scene />
          {/* <OrbitControls enablePan={false} enableZoom={false} maxPolarAngle={Math.PI / 2} minPolarAngle={Math.PI / 2} /> */}
        </Canvas>
      </main>
    </div>
  );
}
